#pragma once
#include <iostream>
#include <iterator>
#include <ranges>
#include <vector>
#include <bitset>
#include <list>
#include <chrono>
#include <unordered_map>
#include <map>
#include <set>
#include <algorithm>
#include <numeric>
#include <cmath>
#include <sstream>
#include <stack>
#include <unordered_set>
#include <atomic>
#include <thread>
#include <execution>
#include <span>
#include <regex>
#include <fstream>
#include <array>
#include <functional>